"""Project/worker scaffolding + detached loop launch.

``do_new`` writes the on-disk layout a project needs; ``spawn_loop`` launches a
worker's outer loop detached in its own process group. Both are libraries the
``danus`` CLI verbs (``danus.orchestration``) call — kept here beside the loop +
layout so the file names, config template, and launch mechanism live in one place.

Notes:
  - the codex MCP wiring launches the installed package ``python -m danus.gateway``
    (a pinned interface) rather than an absolute path to a server file;
  - the config template + defaults (verify URL, model) come from env at CALL time
    (with a built-in fallback default), not hard-wired at import time.
"""

from __future__ import annotations

import json
import os
import stat
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Optional

from danus import codex

from . import layout as L

# --------------------------------------------------------------------------- #
# atomic file helpers                                                         #
# --------------------------------------------------------------------------- #

def atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    parent_info = os.lstat(path.parent)
    if stat.S_ISLNK(parent_info.st_mode) or not stat.S_ISDIR(parent_info.st_mode):
        raise OSError(f"refusing unsafe write parent: {path.parent}")
    if not hasattr(os, "O_NOFOLLOW") or not hasattr(os, "O_DIRECTORY"):
        raise OSError("host lacks no-follow file operations")
    parent_fd = os.open(
        str(path.parent), os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW
    )
    temp_name = f".{path.name}.danus-{os.getpid()}-{os.urandom(12).hex()}"
    temp_fd: Optional[int] = None
    try:
        temp_fd = os.open(
            temp_name,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW,
            0o600,
            dir_fd=parent_fd,
        )
        payload = text.encode("utf-8")
        offset = 0
        while offset < len(payload):
            offset += os.write(temp_fd, payload[offset:])
        os.fsync(temp_fd)
        os.close(temp_fd)
        temp_fd = None
        os.replace(
            temp_name,
            path.name,
            src_dir_fd=parent_fd,
            dst_dir_fd=parent_fd,
        )
        os.fsync(parent_fd)
    finally:
        if temp_fd is not None:
            os.close(temp_fd)
        try:
            os.unlink(temp_name, dir_fd=parent_fd)
        except FileNotFoundError:
            pass
        os.close(parent_fd)


def ensure_real_dir(path: Path, *, mode: int = 0o700) -> None:
    try:
        os.mkdir(path, mode)
    except FileExistsError:
        pass
    info = os.lstat(path)
    if stat.S_ISLNK(info.st_mode) or not stat.S_ISDIR(info.st_mode):
        raise OSError(f"refusing unsafe directory: {path}")
    os.chmod(path, mode)


def open_append_log(path: Path):
    """Open a host log without following a model-planted link/hardlink."""
    ensure_real_dir(path.parent)
    fd = os.open(
        str(path),
        os.O_WRONLY
        | os.O_CREAT
        | os.O_APPEND
        | os.O_NOFOLLOW
        | os.O_NONBLOCK,
        0o600,
    )
    info = os.fstat(fd)
    if not stat.S_ISREG(info.st_mode) or info.st_nlink != 1:
        os.close(fd)
        raise OSError(f"refusing unsafe log file: {path}")
    return os.fdopen(fd, "a", encoding="utf-8")


def _toml_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def symlink(target: Path, link: Path) -> None:
    """Best-effort symlink; degrade gracefully where symlinks are unsupported
    (the codex config still points at the repo, so the worker isn't broken)."""
    if link.is_symlink() or link.exists():
        return
    try:
        os.symlink(target, link)
    except OSError:
        pass


# --------------------------------------------------------------------------- #
# codex config template + task placeholder                                    #
# --------------------------------------------------------------------------- #

# The MCP server is the installed danus gateway (role=worker) launched as a
# module — pinned interface (ARCHITECTURE.md §4): `python -m danus.gateway` +
# DANUS_ROLE. `command` is the interpreter the worker loop itself runs on
# (sys.executable — the same Python danus was launched with), so the gateway can
# never resolve to a different `python3` on codex's PATH. It is rewritten every
# time the loop starts, so a moved/rebuilt venv is picked up automatically.
# Isolated mode also prevents a worker-local shadow package from replacing Danus.
_CODEX_CONFIG = """\
# Auto-generated by danus (rewritten each time the worker loop starts); do not hand-edit.
[mcp_servers.danus]
command = {python}
args = ["-I", "-B", "-m", "danus.gateway"]
default_tools_approval_mode = "approve"
required = true
# fact_submit blocks on the verify service (a cold-started codex that can reason
# for minutes on a hard proof); codex's default tool-call timeout is 120s, which
# would abort those legitimate long verifications. Match the verify HTTP timeout.
tool_timeout_sec = 3600

[mcp_servers.danus.env]
DANUS_PROJECT_DIR = {project_dir}
DANUS_AUTHOR = {author}
DANUS_ROLE = "worker"
DANUS_HOTJOIN_ENABLED = "1"
DANUS_HOTJOIN_TARGET = {author}
DANUS_VERIFY_URL = {verify_url}
"""

_TASK_PLACEHOLDER = (
    "# Task\n\n(unassigned — the main agent writes your assignment here via "
    "`danus assign`; you read this file at the start of every round)\n"
)


def _verify_url() -> str:
    # each fact_submit POSTs here; the verify service spawns a fresh codex to
    # verify. Standard local endpoint by default; override with DANUS_VERIFY_URL.
    return os.environ.get("DANUS_VERIFY_URL", "http://127.0.0.1:8091/verify")


def _default_model() -> str:
    return codex.model()


def write_codex_config(wl: "L.WorkerLayout") -> None:
    """Write the worker's ``.codex/config.toml``, pinning the gateway ``command``
    to THIS interpreter (``sys.executable``). Used at scaffold time and rewritten
    at every loop start (see ``loop.main``), so the worker's gateway always runs on
    the same Python as danus — never a bare ``python3`` that PATH could resolve to
    a different install (which would silently point the worker at another codebase
    / an incompatible ``mcp``)."""
    atomic_write(wl.codex_config, _CODEX_CONFIG.format(
        python=_toml_str(sys.executable),
        project_dir=_toml_str(str(wl.project_dir)),
        author=_toml_str(wl.name),
        verify_url=_toml_str(_verify_url()),
    ))


# --------------------------------------------------------------------------- #
# do_new — scaffold a project                                                 #
# --------------------------------------------------------------------------- #

def do_new(project: str, roles: str = "high:3,xhigh:4",
           model: Optional[str] = None) -> Dict:
    """Scaffold a project dir + one worker home per role. Refuses to clobber an
    existing project dir (no silent overwrite of a live fact graph). Returns
    ``{"project_dir", "workers"}``."""
    try:
        project = L.validate_segment(project, label="project")
    except ValueError as exc:
        raise SystemExit(f"invalid project name: {exc}") from exc
    pdir = L.project_dir(project)
    if pdir.exists():
        raise SystemExit(f"project already exists: {pdir} (pick another name or remove it)")
    role_pairs = L.parse_roles(roles)
    model = model or _default_model()

    L.workers_dir(project).mkdir(parents=True, exist_ok=True)
    (pdir / "global_memory").mkdir(exist_ok=True)
    (pdir / "fact_graph").mkdir(exist_ok=True)

    created: List[str] = []
    for worker, base in role_pairs:
        wl = L.WorkerLayout(L.worker_dir(project, worker))
        wl.local_memory.mkdir(parents=True, exist_ok=True)
        wl.logs.mkdir(exist_ok=True)

        # static contract + skills (symlinks stay in sync with the repo)
        symlink(L.worker_md(), wl.dir / "AGENTS.md")
        (wl.dir / ".agents").mkdir(exist_ok=True)
        symlink(L.worker_skills_dir(), wl.dir / ".agents" / "skills")

        # codex MCP wiring (role=worker)
        write_codex_config(wl)
        atomic_write(wl.task, _TASK_PLACEHOLDER)
        atomic_write(wl.role,
                     f"MODEL={model}\nREASONING_EFFORT={base}\nROLE={base}\nDANUS_AUTHOR={worker}\n")
        atomic_write(wl.status,
                     json.dumps({"worker": worker, "state": "created", "round": 0}, indent=2))
        created.append(worker)

    meta = {"name": project, "model": model, "roles": roles, "workers": created}
    atomic_write(pdir / "project.json", json.dumps(meta, ensure_ascii=False, indent=2))
    return {"project_dir": str(pdir), "workers": created}


# --------------------------------------------------------------------------- #
# spawn_loop — detached launch of one worker's outer loop                     #
# --------------------------------------------------------------------------- #

def spawn_loop(wdir: Path) -> subprocess.Popen:
    """Launch ``python -m danus.execution <wdir>`` detached in its own process
    group (``start_new_session=True``).  ``danus stop --force`` never sends a
    numeric PID/PGID signal: it writes a durable cooperative request, and the
    authenticated loop cleans its separately owned Codex process group.  The
    live ``Popen`` handle keeps a direct-child/reaping fence until the kernel
    birth record is durable."""
    wl = L.WorkerLayout(wdir)
    logf = open_append_log(wl.logs / "loop.log")
    try:
        proc = subprocess.Popen(
            [sys.executable, "-m", "danus.execution", str(wdir)],
            stdout=logf, stderr=subprocess.STDOUT, stdin=subprocess.DEVNULL,
            start_new_session=True,
        )
    finally:
        logf.close()
    return proc
